runtime: custom
env: flex
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/gcloud-angular-ci-cd/index.html
    upload: dist/gcloud-angular-ci-cd/index.html

  - url: /
    static_dir: dist/gcloud-angular-ci-cd/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
